# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4bf95ec6fadd4d5a0eeabf6f9f35231f"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "sample-should-render"
handle = "sample-should-render"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "vulpes1.myshopify.com"
include_config_on_deploy = true
